### PR TITLE
Full support EventsExecutor + IPC Actions/Clients/Services

### PR DESCRIPTION
**Pull request by mauropasse**

### CODE REVIEW

**Comment by alsora** [comment]
I did a quick look and the PR seems good.
However, I noticed that the intra-process action client and action servers are in the rclcpp library.
How complex do you think is it to move them to the rclcpp_action library?

**Comment by mauropasse** [comment]
I think they live in the `experimental` folder just because the IPC for pub/sub was there, and was the quickest way to have it running.
It should be possible to have them on the `rclcpp_action` library, but not sure about issues of circular dependencies.
It needs to be revised for that, I can check when I have some time

**Comment by mauropasse** [comment]
The `ros2/rclcpp/rclcpp/include/rclcpp/experimental/intra_process_manager.hpp` has includes like:
```
#include "rclcpp/experimental/action_client_intra_process.hpp"
#include "rclcpp/experimental/action_client_intra_process_base.hpp"
#include "rclcpp/experimental/action_server_intra_process.hpp"
#include "rclcpp/experimental/action_server_intra_process_base.hpp"
#include "rclcpp/experimental/client_intra_process.hpp"
#include "rclcpp/experimental/client_intra_process_base.hpp"
```
If those lived only on `rclcpp_action`, then `rclcpp` would depend on them, creating a circular dependency. Right?

**Comment by alsora** [comment]
Yes, in order to support this, the intra-process manager would need to not have a dependency on ipc actions.
I don't care about this, but it will definitely be pointed out in a comment for your rclcpp PR.

I'm not sure how to achieve this.. The work may require to reorganize the intra-process manager to support generic entities.

**Pull request merged**
